name: Log stuff

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/its-local
        with:
          message: 'Hello from action 👋'
