name: Code Audit

on: [push, pull_request]

defaults:
  run:
    working-directory: exercise-1

jobs:
  lint:
    name: test all the things
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm ci

      - name: lint code
        run: npm run lint
