name: Code Audit

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    working-directory: ./exercise-1 
    steps:
    - uses: actions/checkout@master
    - name: npm ci
      run: npm ci
    - name: lint
      run: npm run lint