name: Frank's tests
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./exercise-1
      - name: Audit
        run: npm run lint
        working-directory: ./exercise-1

