name: Code Audit

on: [push, pull_request]

defaults:
  run:
    working-directory: exercise-1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install dependencies
        run: npm i

      - name: Lint code
        run: npm run lint
