name: Code Audit
on: push

defaults:
  run:
    working-directory: exercise-1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dep
        run: npm i
      - name: lint
        run: npm run lint
