name: local action
on: pull_request
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: its-local
        uses: ./exercise-2/its-local
        with:
          message: 'hello world'
