name: Log stuff

on: push

jobs:
  show-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./exercise-2/its-local
        with:
          message: 'Hello from action 👋'