name: Log stuff

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./exercise-2/it-local
        with:
          message: 'It is Friday!'
